export { default as PageContainer } from './ui/PageContainer.vue'
export { default as PageTitle } from './ui/PageTitle.vue'
export { default as PageHeader } from './ui/PageHeader.vue'
export { default as PageBody } from './ui/PageBody.vue'
export { default as PageFooter } from './ui/PageFooter.vue'
